### ISSUE TITLE
Update templates based on other packages

### ISSUE THREAD

**Issue by jklenzing** [pysat/pysatEcosystem_Template#3]
- [x] pysatCDAAC
- [x] pysatMadrigal
- [x] pysatMissions
- [x] pysatModels
- [x] pysatNASA
- [x] pysatSeasons
- [x] pysatSpaceWeather
- [x] pysat

**Comment by aburrell** [comment]
@jklenzing pysatSeasons is not going to be "ahead" of this repository, should we consider this task completed?

**Comment by jklenzing** [comment]
> @jklenzing pysatSeasons is not going to be "ahead" of this repository, should we consider this task completed?

I think so. Thanks!
