### ISSUE TITLE
Prep for release of v0.0.1

### ISSUE THREAD

**Issue by jklenzing** [pysat/pysatEcosystem_Template#5]
- [x] ~~zenodo~~
- [x] announcement to slack

**Comment by aburrell** [comment]
This is just a central repository for templates right?  So we don't need a zenodo for it, do we?

**Comment by jklenzing** [comment]
Probably not.  was thinking we should probably version this for our sanity though

**Comment by aburrell** [comment]
We can just do that with versioned releases.  No need to DOI it and impact our ORCiDs.
