### ISSUE TITLE
QUESTION: how to run GA tests for outside contributors

### ISSUE THREAD

**Issue by jklenzing** [pysat/pysatEcosystem_Template#7]
**Is your feature request related to a problem? Please describe.**
The contributing guidelines are currently written assuming that outside contributors can run GA tests automatically.  From experience in pysat/pysatNASA#139, this needs to be initiated by a member of the team.

**Describe the solution you'd like**
Update the docs to explain this.

**Describe alternatives you've considered**
Can GA be configured to run automatically for all?  Do we want this instead?

**Additional context**
n/a

**Comment by jklenzing** [comment]
pinging @rstoneback, @aburrell, @JonathonMSmith for discussion.

**Comment by JonathonMSmith** [comment]
I'm not sure this has the answer to the first question but I think the permissions/access to GA is [configurable](https://docs.github.com/en/organizations/managing-organization-settings/disabling-or-limiting-github-actions-for-your-organization).

As for what everyone wants. I'm usually of the mind that we can leave permissions very open until there's a problem with excessive GA test runs.

**Comment by jklenzing** [comment]
Updated contributing doc to reflect. 99737b73ce18d6573a98ed0bd63826cfcfd801c5
